package com.adins.mss.dao;

import com.adins.mss.base.util.ExcludeFromGson;
import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TR_RECEIPTHISTORY".
 */
public class ReceiptHistory {

    /** Not-null value. */
     @SerializedName("uuid_receipt_history")
    private String uuid_receipt_history;
     @SerializedName("uuid_task_h")
    private String uuid_task_h;
     @SerializedName("agreementNo")
    private String agreement_no;
     @SerializedName("invoiceNo")
    private String receipt_no;
     @SerializedName("valueDt")
    private String payment_date;

    public ReceiptHistory() {
    }

    public ReceiptHistory(String uuid_receipt_history) {
        this.uuid_receipt_history = uuid_receipt_history;
    }

    public ReceiptHistory(String uuid_receipt_history, String uuid_task_h, String agreement_no, String receipt_no, String payment_date) {
        this.uuid_receipt_history = uuid_receipt_history;
        this.uuid_task_h = uuid_task_h;
        this.agreement_no = agreement_no;
        this.receipt_no = receipt_no;
        this.payment_date = payment_date;
    }

    /** Not-null value. */
    public String getUuid_receipt_history() {
        return uuid_receipt_history;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid_receipt_history(String uuid_receipt_history) {
        this.uuid_receipt_history = uuid_receipt_history;
    }

    public String getUuid_task_h() {
        return uuid_task_h;
    }

    public void setUuid_task_h(String uuid_task_h) {
        this.uuid_task_h = uuid_task_h;
    }

    public String getAgreement_no() {
        return agreement_no;
    }

    public void setAgreement_no(String agreement_no) {
        this.agreement_no = agreement_no;
    }

    public String getReceipt_no() {
        return receipt_no;
    }

    public void setReceipt_no(String receipt_no) {
        this.receipt_no = receipt_no;
    }

    public String getPayment_date() {
        return payment_date;
    }

    public void setPayment_date(String payment_date) {
        this.payment_date = payment_date;
    }

}
