package com.adins.mss.dao;

import com.adins.mss.base.util.ExcludeFromGson;
import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MS_CONTACT".
 */
public class Contact {

    /** Not-null value. */
     @SerializedName("uuid_contact")
    private String uuid_contact;
     @SerializedName("contact_name")
    private String contact_name;
     @SerializedName("contact_dept")
    private String contact_dept;
     @SerializedName("contact_phone")
    private String contact_phone;
     @SerializedName("contact_email")
    private String contact_email;
     @SerializedName("uuid_account")
    private String uuid_account;
     @SerializedName("dtm_crt")
    private java.util.Date dtm_crt;

    public Contact() {
    }

    public Contact(String uuid_contact) {
        this.uuid_contact = uuid_contact;
    }

    public Contact(String uuid_contact, String contact_name, String contact_dept, String contact_phone, String contact_email, String uuid_account, java.util.Date dtm_crt) {
        this.uuid_contact = uuid_contact;
        this.contact_name = contact_name;
        this.contact_dept = contact_dept;
        this.contact_phone = contact_phone;
        this.contact_email = contact_email;
        this.uuid_account = uuid_account;
        this.dtm_crt = dtm_crt;
    }

    /** Not-null value. */
    public String getUuid_contact() {
        return uuid_contact;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid_contact(String uuid_contact) {
        this.uuid_contact = uuid_contact;
    }

    public String getContact_name() {
        return contact_name;
    }

    public void setContact_name(String contact_name) {
        this.contact_name = contact_name;
    }

    public String getContact_dept() {
        return contact_dept;
    }

    public void setContact_dept(String contact_dept) {
        this.contact_dept = contact_dept;
    }

    public String getContact_phone() {
        return contact_phone;
    }

    public void setContact_phone(String contact_phone) {
        this.contact_phone = contact_phone;
    }

    public String getContact_email() {
        return contact_email;
    }

    public void setContact_email(String contact_email) {
        this.contact_email = contact_email;
    }

    public String getUuid_account() {
        return uuid_account;
    }

    public void setUuid_account(String uuid_account) {
        this.uuid_account = uuid_account;
    }

    public java.util.Date getDtm_crt() {
        return dtm_crt;
    }

    public void setDtm_crt(java.util.Date dtm_crt) {
        this.dtm_crt = dtm_crt;
    }

}
