package com.adins.mss.dao;

import com.adins.mss.base.util.ExcludeFromGson;
import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "TR_LOGO_PRINT".
 */
public class LogoPrint {

    /** Not-null value. */
     @SerializedName("uuid_logo_print")
    private String uuid_logo_print;
    /** Not-null value. */
     @SerializedName("tenant")
    private String tenant;
     @SerializedName("image_bitmap")
    private byte[] image_bitmap;

    public LogoPrint() {
    }

    public LogoPrint(String uuid_logo_print) {
        this.uuid_logo_print = uuid_logo_print;
    }

    public LogoPrint(String uuid_logo_print, String tenant, byte[] image_bitmap) {
        this.uuid_logo_print = uuid_logo_print;
        this.tenant = tenant;
        this.image_bitmap = image_bitmap;
    }

    /** Not-null value. */
    public String getUuid_logo_print() {
        return uuid_logo_print;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid_logo_print(String uuid_logo_print) {
        this.uuid_logo_print = uuid_logo_print;
    }

    /** Not-null value. */
    public String getTenant() {
        return tenant;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTenant(String tenant) {
        this.tenant = tenant;
    }

    public byte[] getImage_bitmap() {
        return image_bitmap;
    }

    public void setImage_bitmap(byte[] image_bitmap) {
        this.image_bitmap = image_bitmap;
    }

}
