name: "AI Code Review Action with Language Settings"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  language:
    description: "Natural language for the code review comments."
    required: false
    default: "english"
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: "**/*.json, **/*.md, yarn.lock, package-lock.json"
runs:
  using: "node20"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
