package com.adins.mss.dao;

import com.adins.mss.base.util.ExcludeFromGson;
import com.google.gson.annotations.SerializedName;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "MS_BANKACCOUNTOFBRANCH".
 */
public class BankAccountOfBranch {

    /** Not-null value. */
     @SerializedName("uuid_bankaccountofbranch")
    private String uuid_bankaccountofbranch;
     @SerializedName("bank_account_id")
    private String bank_account_id;
     @SerializedName("bank_account_no")
    private String bank_account_no;
     @SerializedName("bank_account_name")
    private String bank_account_name;
     @SerializedName("branch_code")
    private String branch_code;

    public BankAccountOfBranch() {
    }

    public BankAccountOfBranch(String uuid_bankaccountofbranch) {
        this.uuid_bankaccountofbranch = uuid_bankaccountofbranch;
    }

    public BankAccountOfBranch(String uuid_bankaccountofbranch, String bank_account_id, String bank_account_no, String bank_account_name, String branch_code) {
        this.uuid_bankaccountofbranch = uuid_bankaccountofbranch;
        this.bank_account_id = bank_account_id;
        this.bank_account_no = bank_account_no;
        this.bank_account_name = bank_account_name;
        this.branch_code = branch_code;
    }

    /** Not-null value. */
    public String getUuid_bankaccountofbranch() {
        return uuid_bankaccountofbranch;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid_bankaccountofbranch(String uuid_bankaccountofbranch) {
        this.uuid_bankaccountofbranch = uuid_bankaccountofbranch;
    }

    public String getBank_account_id() {
        return bank_account_id;
    }

    public void setBank_account_id(String bank_account_id) {
        this.bank_account_id = bank_account_id;
    }

    public String getBank_account_no() {
        return bank_account_no;
    }

    public void setBank_account_no(String bank_account_no) {
        this.bank_account_no = bank_account_no;
    }

    public String getBank_account_name() {
        return bank_account_name;
    }

    public void setBank_account_name(String bank_account_name) {
        this.bank_account_name = bank_account_name;
    }

    public String getBranch_code() {
        return branch_code;
    }

    public void setBranch_code(String branch_code) {
        this.branch_code = branch_code;
    }

}
