package com.adins.mss.dao;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.adins.mss.dao.CollectionActivity;
import com.adins.mss.dao.InstallmentSchedule;
import com.adins.mss.dao.MobileDataFile;
import com.adins.mss.dao.GeneralParameter;
import com.adins.mss.dao.GroupUser;
import com.adins.mss.dao.Lookup;
import com.adins.mss.dao.Sync;
import com.adins.mss.dao.Menu;
import com.adins.mss.dao.PrintItem;
import com.adins.mss.dao.QuestionSet;
import com.adins.mss.dao.Scheme;
import com.adins.mss.dao.TimelineType;
import com.adins.mss.dao.User;
import com.adins.mss.dao.Kompetisi;
import com.adins.mss.dao.Logger;
import com.adins.mss.dao.CollectionHistory;
import com.adins.mss.dao.Comment;
import com.adins.mss.dao.DepositReportD;
import com.adins.mss.dao.DepositReportH;
import com.adins.mss.dao.ImageResult;
import com.adins.mss.dao.LocationInfo;
import com.adins.mss.dao.Message;
import com.adins.mss.dao.PaymentHistoryD;
import com.adins.mss.dao.PaymentHistoryH;
import com.adins.mss.dao.PaymentChannel;
import com.adins.mss.dao.PrintResult;
import com.adins.mss.dao.ReceiptVoucher;
import com.adins.mss.dao.TaskSummary;
import com.adins.mss.dao.TaskD;
import com.adins.mss.dao.TaskH;
import com.adins.mss.dao.TaskHSequence;
import com.adins.mss.dao.PlanTask;
import com.adins.mss.dao.Timeline;
import com.adins.mss.dao.MobileContentD;
import com.adins.mss.dao.MobileContentH;
import com.adins.mss.dao.Holiday;
import com.adins.mss.dao.PrintDate;
import com.adins.mss.dao.ErrorLog;
import com.adins.mss.dao.Account;
import com.adins.mss.dao.Product;
import com.adins.mss.dao.Contact;
import com.adins.mss.dao.GroupTask;
import com.adins.mss.dao.Catalogue;
import com.adins.mss.dao.ThemeItem;
import com.adins.mss.dao.Theme;
import com.adins.mss.dao.LogoPrint;
import com.adins.mss.dao.Emergency;
import com.adins.mss.dao.LastSync;
import com.adins.mss.dao.BankAccountOfBranch;
import com.adins.mss.dao.Broadcast;
import com.adins.mss.dao.ReceiptHistory;

import com.adins.mss.dao.CollectionActivityDao;
import com.adins.mss.dao.InstallmentScheduleDao;
import com.adins.mss.dao.MobileDataFileDao;
import com.adins.mss.dao.GeneralParameterDao;
import com.adins.mss.dao.GroupUserDao;
import com.adins.mss.dao.LookupDao;
import com.adins.mss.dao.SyncDao;
import com.adins.mss.dao.MenuDao;
import com.adins.mss.dao.PrintItemDao;
import com.adins.mss.dao.QuestionSetDao;
import com.adins.mss.dao.SchemeDao;
import com.adins.mss.dao.TimelineTypeDao;
import com.adins.mss.dao.UserDao;
import com.adins.mss.dao.KompetisiDao;
import com.adins.mss.dao.LoggerDao;
import com.adins.mss.dao.CollectionHistoryDao;
import com.adins.mss.dao.CommentDao;
import com.adins.mss.dao.DepositReportDDao;
import com.adins.mss.dao.DepositReportHDao;
import com.adins.mss.dao.ImageResultDao;
import com.adins.mss.dao.LocationInfoDao;
import com.adins.mss.dao.MessageDao;
import com.adins.mss.dao.PaymentHistoryDDao;
import com.adins.mss.dao.PaymentHistoryHDao;
import com.adins.mss.dao.PaymentChannelDao;
import com.adins.mss.dao.PrintResultDao;
import com.adins.mss.dao.ReceiptVoucherDao;
import com.adins.mss.dao.TaskSummaryDao;
import com.adins.mss.dao.TaskDDao;
import com.adins.mss.dao.TaskHDao;
import com.adins.mss.dao.TaskHSequenceDao;
import com.adins.mss.dao.PlanTaskDao;
import com.adins.mss.dao.TimelineDao;
import com.adins.mss.dao.MobileContentDDao;
import com.adins.mss.dao.MobileContentHDao;
import com.adins.mss.dao.HolidayDao;
import com.adins.mss.dao.PrintDateDao;
import com.adins.mss.dao.ErrorLogDao;
import com.adins.mss.dao.AccountDao;
import com.adins.mss.dao.ProductDao;
import com.adins.mss.dao.ContactDao;
import com.adins.mss.dao.GroupTaskDao;
import com.adins.mss.dao.CatalogueDao;
import com.adins.mss.dao.ThemeItemDao;
import com.adins.mss.dao.ThemeDao;
import com.adins.mss.dao.LogoPrintDao;
import com.adins.mss.dao.EmergencyDao;
import com.adins.mss.dao.LastSyncDao;
import com.adins.mss.dao.BankAccountOfBranchDao;
import com.adins.mss.dao.BroadcastDao;
import com.adins.mss.dao.ReceiptHistoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig collectionActivityDaoConfig;
    private final DaoConfig installmentScheduleDaoConfig;
    private final DaoConfig mobileDataFileDaoConfig;
    private final DaoConfig generalParameterDaoConfig;
    private final DaoConfig groupUserDaoConfig;
    private final DaoConfig lookupDaoConfig;
    private final DaoConfig syncDaoConfig;
    private final DaoConfig menuDaoConfig;
    private final DaoConfig printItemDaoConfig;
    private final DaoConfig questionSetDaoConfig;
    private final DaoConfig schemeDaoConfig;
    private final DaoConfig timelineTypeDaoConfig;
    private final DaoConfig userDaoConfig;
    private final DaoConfig kompetisiDaoConfig;
    private final DaoConfig loggerDaoConfig;
    private final DaoConfig collectionHistoryDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig depositReportDDaoConfig;
    private final DaoConfig depositReportHDaoConfig;
    private final DaoConfig imageResultDaoConfig;
    private final DaoConfig locationInfoDaoConfig;
    private final DaoConfig messageDaoConfig;
    private final DaoConfig paymentHistoryDDaoConfig;
    private final DaoConfig paymentHistoryHDaoConfig;
    private final DaoConfig paymentChannelDaoConfig;
    private final DaoConfig printResultDaoConfig;
    private final DaoConfig receiptVoucherDaoConfig;
    private final DaoConfig taskSummaryDaoConfig;
    private final DaoConfig taskDDaoConfig;
    private final DaoConfig taskHDaoConfig;
    private final DaoConfig taskHSequenceDaoConfig;
    private final DaoConfig planTaskDaoConfig;
    private final DaoConfig timelineDaoConfig;
    private final DaoConfig mobileContentDDaoConfig;
    private final DaoConfig mobileContentHDaoConfig;
    private final DaoConfig holidayDaoConfig;
    private final DaoConfig printDateDaoConfig;
    private final DaoConfig errorLogDaoConfig;
    private final DaoConfig accountDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig groupTaskDaoConfig;
    private final DaoConfig catalogueDaoConfig;
    private final DaoConfig themeItemDaoConfig;
    private final DaoConfig themeDaoConfig;
    private final DaoConfig logoPrintDaoConfig;
    private final DaoConfig emergencyDaoConfig;
    private final DaoConfig lastSyncDaoConfig;
    private final DaoConfig bankAccountOfBranchDaoConfig;
    private final DaoConfig broadcastDaoConfig;
    private final DaoConfig receiptHistoryDaoConfig;

    private final CollectionActivityDao collectionActivityDao;
    private final InstallmentScheduleDao installmentScheduleDao;
    private final MobileDataFileDao mobileDataFileDao;
    private final GeneralParameterDao generalParameterDao;
    private final GroupUserDao groupUserDao;
    private final LookupDao lookupDao;
    private final SyncDao syncDao;
    private final MenuDao menuDao;
    private final PrintItemDao printItemDao;
    private final QuestionSetDao questionSetDao;
    private final SchemeDao schemeDao;
    private final TimelineTypeDao timelineTypeDao;
    private final UserDao userDao;
    private final KompetisiDao kompetisiDao;
    private final LoggerDao loggerDao;
    private final CollectionHistoryDao collectionHistoryDao;
    private final CommentDao commentDao;
    private final DepositReportDDao depositReportDDao;
    private final DepositReportHDao depositReportHDao;
    private final ImageResultDao imageResultDao;
    private final LocationInfoDao locationInfoDao;
    private final MessageDao messageDao;
    private final PaymentHistoryDDao paymentHistoryDDao;
    private final PaymentHistoryHDao paymentHistoryHDao;
    private final PaymentChannelDao paymentChannelDao;
    private final PrintResultDao printResultDao;
    private final ReceiptVoucherDao receiptVoucherDao;
    private final TaskSummaryDao taskSummaryDao;
    private final TaskDDao taskDDao;
    private final TaskHDao taskHDao;
    private final TaskHSequenceDao taskHSequenceDao;
    private final PlanTaskDao planTaskDao;
    private final TimelineDao timelineDao;
    private final MobileContentDDao mobileContentDDao;
    private final MobileContentHDao mobileContentHDao;
    private final HolidayDao holidayDao;
    private final PrintDateDao printDateDao;
    private final ErrorLogDao errorLogDao;
    private final AccountDao accountDao;
    private final ProductDao productDao;
    private final ContactDao contactDao;
    private final GroupTaskDao groupTaskDao;
    private final CatalogueDao catalogueDao;
    private final ThemeItemDao themeItemDao;
    private final ThemeDao themeDao;
    private final LogoPrintDao logoPrintDao;
    private final EmergencyDao emergencyDao;
    private final LastSyncDao lastSyncDao;
    private final BankAccountOfBranchDao bankAccountOfBranchDao;
    private final BroadcastDao broadcastDao;
    private final ReceiptHistoryDao receiptHistoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        collectionActivityDaoConfig = daoConfigMap.get(CollectionActivityDao.class).clone();
        collectionActivityDaoConfig.initIdentityScope(type);

        installmentScheduleDaoConfig = daoConfigMap.get(InstallmentScheduleDao.class).clone();
        installmentScheduleDaoConfig.initIdentityScope(type);

        mobileDataFileDaoConfig = daoConfigMap.get(MobileDataFileDao.class).clone();
        mobileDataFileDaoConfig.initIdentityScope(type);

        generalParameterDaoConfig = daoConfigMap.get(GeneralParameterDao.class).clone();
        generalParameterDaoConfig.initIdentityScope(type);

        groupUserDaoConfig = daoConfigMap.get(GroupUserDao.class).clone();
        groupUserDaoConfig.initIdentityScope(type);

        lookupDaoConfig = daoConfigMap.get(LookupDao.class).clone();
        lookupDaoConfig.initIdentityScope(type);

        syncDaoConfig = daoConfigMap.get(SyncDao.class).clone();
        syncDaoConfig.initIdentityScope(type);

        menuDaoConfig = daoConfigMap.get(MenuDao.class).clone();
        menuDaoConfig.initIdentityScope(type);

        printItemDaoConfig = daoConfigMap.get(PrintItemDao.class).clone();
        printItemDaoConfig.initIdentityScope(type);

        questionSetDaoConfig = daoConfigMap.get(QuestionSetDao.class).clone();
        questionSetDaoConfig.initIdentityScope(type);

        schemeDaoConfig = daoConfigMap.get(SchemeDao.class).clone();
        schemeDaoConfig.initIdentityScope(type);

        timelineTypeDaoConfig = daoConfigMap.get(TimelineTypeDao.class).clone();
        timelineTypeDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        kompetisiDaoConfig = daoConfigMap.get(KompetisiDao.class).clone();
        kompetisiDaoConfig.initIdentityScope(type);

        loggerDaoConfig = daoConfigMap.get(LoggerDao.class).clone();
        loggerDaoConfig.initIdentityScope(type);

        collectionHistoryDaoConfig = daoConfigMap.get(CollectionHistoryDao.class).clone();
        collectionHistoryDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        depositReportDDaoConfig = daoConfigMap.get(DepositReportDDao.class).clone();
        depositReportDDaoConfig.initIdentityScope(type);

        depositReportHDaoConfig = daoConfigMap.get(DepositReportHDao.class).clone();
        depositReportHDaoConfig.initIdentityScope(type);

        imageResultDaoConfig = daoConfigMap.get(ImageResultDao.class).clone();
        imageResultDaoConfig.initIdentityScope(type);

        locationInfoDaoConfig = daoConfigMap.get(LocationInfoDao.class).clone();
        locationInfoDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        paymentHistoryDDaoConfig = daoConfigMap.get(PaymentHistoryDDao.class).clone();
        paymentHistoryDDaoConfig.initIdentityScope(type);

        paymentHistoryHDaoConfig = daoConfigMap.get(PaymentHistoryHDao.class).clone();
        paymentHistoryHDaoConfig.initIdentityScope(type);

        paymentChannelDaoConfig = daoConfigMap.get(PaymentChannelDao.class).clone();
        paymentChannelDaoConfig.initIdentityScope(type);

        printResultDaoConfig = daoConfigMap.get(PrintResultDao.class).clone();
        printResultDaoConfig.initIdentityScope(type);

        receiptVoucherDaoConfig = daoConfigMap.get(ReceiptVoucherDao.class).clone();
        receiptVoucherDaoConfig.initIdentityScope(type);

        taskSummaryDaoConfig = daoConfigMap.get(TaskSummaryDao.class).clone();
        taskSummaryDaoConfig.initIdentityScope(type);

        taskDDaoConfig = daoConfigMap.get(TaskDDao.class).clone();
        taskDDaoConfig.initIdentityScope(type);

        taskHDaoConfig = daoConfigMap.get(TaskHDao.class).clone();
        taskHDaoConfig.initIdentityScope(type);

        taskHSequenceDaoConfig = daoConfigMap.get(TaskHSequenceDao.class).clone();
        taskHSequenceDaoConfig.initIdentityScope(type);

        planTaskDaoConfig = daoConfigMap.get(PlanTaskDao.class).clone();
        planTaskDaoConfig.initIdentityScope(type);

        timelineDaoConfig = daoConfigMap.get(TimelineDao.class).clone();
        timelineDaoConfig.initIdentityScope(type);

        mobileContentDDaoConfig = daoConfigMap.get(MobileContentDDao.class).clone();
        mobileContentDDaoConfig.initIdentityScope(type);

        mobileContentHDaoConfig = daoConfigMap.get(MobileContentHDao.class).clone();
        mobileContentHDaoConfig.initIdentityScope(type);

        holidayDaoConfig = daoConfigMap.get(HolidayDao.class).clone();
        holidayDaoConfig.initIdentityScope(type);

        printDateDaoConfig = daoConfigMap.get(PrintDateDao.class).clone();
        printDateDaoConfig.initIdentityScope(type);

        errorLogDaoConfig = daoConfigMap.get(ErrorLogDao.class).clone();
        errorLogDaoConfig.initIdentityScope(type);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        groupTaskDaoConfig = daoConfigMap.get(GroupTaskDao.class).clone();
        groupTaskDaoConfig.initIdentityScope(type);

        catalogueDaoConfig = daoConfigMap.get(CatalogueDao.class).clone();
        catalogueDaoConfig.initIdentityScope(type);

        themeItemDaoConfig = daoConfigMap.get(ThemeItemDao.class).clone();
        themeItemDaoConfig.initIdentityScope(type);

        themeDaoConfig = daoConfigMap.get(ThemeDao.class).clone();
        themeDaoConfig.initIdentityScope(type);

        logoPrintDaoConfig = daoConfigMap.get(LogoPrintDao.class).clone();
        logoPrintDaoConfig.initIdentityScope(type);

        emergencyDaoConfig = daoConfigMap.get(EmergencyDao.class).clone();
        emergencyDaoConfig.initIdentityScope(type);

        lastSyncDaoConfig = daoConfigMap.get(LastSyncDao.class).clone();
        lastSyncDaoConfig.initIdentityScope(type);

        bankAccountOfBranchDaoConfig = daoConfigMap.get(BankAccountOfBranchDao.class).clone();
        bankAccountOfBranchDaoConfig.initIdentityScope(type);

        broadcastDaoConfig = daoConfigMap.get(BroadcastDao.class).clone();
        broadcastDaoConfig.initIdentityScope(type);

        receiptHistoryDaoConfig = daoConfigMap.get(ReceiptHistoryDao.class).clone();
        receiptHistoryDaoConfig.initIdentityScope(type);

        collectionActivityDao = new CollectionActivityDao(collectionActivityDaoConfig, this);
        installmentScheduleDao = new InstallmentScheduleDao(installmentScheduleDaoConfig, this);
        mobileDataFileDao = new MobileDataFileDao(mobileDataFileDaoConfig, this);
        generalParameterDao = new GeneralParameterDao(generalParameterDaoConfig, this);
        groupUserDao = new GroupUserDao(groupUserDaoConfig, this);
        lookupDao = new LookupDao(lookupDaoConfig, this);
        syncDao = new SyncDao(syncDaoConfig, this);
        menuDao = new MenuDao(menuDaoConfig, this);
        printItemDao = new PrintItemDao(printItemDaoConfig, this);
        questionSetDao = new QuestionSetDao(questionSetDaoConfig, this);
        schemeDao = new SchemeDao(schemeDaoConfig, this);
        timelineTypeDao = new TimelineTypeDao(timelineTypeDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);
        kompetisiDao = new KompetisiDao(kompetisiDaoConfig, this);
        loggerDao = new LoggerDao(loggerDaoConfig, this);
        collectionHistoryDao = new CollectionHistoryDao(collectionHistoryDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        depositReportDDao = new DepositReportDDao(depositReportDDaoConfig, this);
        depositReportHDao = new DepositReportHDao(depositReportHDaoConfig, this);
        imageResultDao = new ImageResultDao(imageResultDaoConfig, this);
        locationInfoDao = new LocationInfoDao(locationInfoDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);
        paymentHistoryDDao = new PaymentHistoryDDao(paymentHistoryDDaoConfig, this);
        paymentHistoryHDao = new PaymentHistoryHDao(paymentHistoryHDaoConfig, this);
        paymentChannelDao = new PaymentChannelDao(paymentChannelDaoConfig, this);
        printResultDao = new PrintResultDao(printResultDaoConfig, this);
        receiptVoucherDao = new ReceiptVoucherDao(receiptVoucherDaoConfig, this);
        taskSummaryDao = new TaskSummaryDao(taskSummaryDaoConfig, this);
        taskDDao = new TaskDDao(taskDDaoConfig, this);
        taskHDao = new TaskHDao(taskHDaoConfig, this);
        taskHSequenceDao = new TaskHSequenceDao(taskHSequenceDaoConfig, this);
        planTaskDao = new PlanTaskDao(planTaskDaoConfig, this);
        timelineDao = new TimelineDao(timelineDaoConfig, this);
        mobileContentDDao = new MobileContentDDao(mobileContentDDaoConfig, this);
        mobileContentHDao = new MobileContentHDao(mobileContentHDaoConfig, this);
        holidayDao = new HolidayDao(holidayDaoConfig, this);
        printDateDao = new PrintDateDao(printDateDaoConfig, this);
        errorLogDao = new ErrorLogDao(errorLogDaoConfig, this);
        accountDao = new AccountDao(accountDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        groupTaskDao = new GroupTaskDao(groupTaskDaoConfig, this);
        catalogueDao = new CatalogueDao(catalogueDaoConfig, this);
        themeItemDao = new ThemeItemDao(themeItemDaoConfig, this);
        themeDao = new ThemeDao(themeDaoConfig, this);
        logoPrintDao = new LogoPrintDao(logoPrintDaoConfig, this);
        emergencyDao = new EmergencyDao(emergencyDaoConfig, this);
        lastSyncDao = new LastSyncDao(lastSyncDaoConfig, this);
        bankAccountOfBranchDao = new BankAccountOfBranchDao(bankAccountOfBranchDaoConfig, this);
        broadcastDao = new BroadcastDao(broadcastDaoConfig, this);
        receiptHistoryDao = new ReceiptHistoryDao(receiptHistoryDaoConfig, this);

        registerDao(CollectionActivity.class, collectionActivityDao);
        registerDao(InstallmentSchedule.class, installmentScheduleDao);
        registerDao(MobileDataFile.class, mobileDataFileDao);
        registerDao(GeneralParameter.class, generalParameterDao);
        registerDao(GroupUser.class, groupUserDao);
        registerDao(Lookup.class, lookupDao);
        registerDao(Sync.class, syncDao);
        registerDao(Menu.class, menuDao);
        registerDao(PrintItem.class, printItemDao);
        registerDao(QuestionSet.class, questionSetDao);
        registerDao(Scheme.class, schemeDao);
        registerDao(TimelineType.class, timelineTypeDao);
        registerDao(User.class, userDao);
        registerDao(Kompetisi.class, kompetisiDao);
        registerDao(Logger.class, loggerDao);
        registerDao(CollectionHistory.class, collectionHistoryDao);
        registerDao(Comment.class, commentDao);
        registerDao(DepositReportD.class, depositReportDDao);
        registerDao(DepositReportH.class, depositReportHDao);
        registerDao(ImageResult.class, imageResultDao);
        registerDao(LocationInfo.class, locationInfoDao);
        registerDao(Message.class, messageDao);
        registerDao(PaymentHistoryD.class, paymentHistoryDDao);
        registerDao(PaymentHistoryH.class, paymentHistoryHDao);
        registerDao(PaymentChannel.class, paymentChannelDao);
        registerDao(PrintResult.class, printResultDao);
        registerDao(ReceiptVoucher.class, receiptVoucherDao);
        registerDao(TaskSummary.class, taskSummaryDao);
        registerDao(TaskD.class, taskDDao);
        registerDao(TaskH.class, taskHDao);
        registerDao(TaskHSequence.class, taskHSequenceDao);
        registerDao(PlanTask.class, planTaskDao);
        registerDao(Timeline.class, timelineDao);
        registerDao(MobileContentD.class, mobileContentDDao);
        registerDao(MobileContentH.class, mobileContentHDao);
        registerDao(Holiday.class, holidayDao);
        registerDao(PrintDate.class, printDateDao);
        registerDao(ErrorLog.class, errorLogDao);
        registerDao(Account.class, accountDao);
        registerDao(Product.class, productDao);
        registerDao(Contact.class, contactDao);
        registerDao(GroupTask.class, groupTaskDao);
        registerDao(Catalogue.class, catalogueDao);
        registerDao(ThemeItem.class, themeItemDao);
        registerDao(Theme.class, themeDao);
        registerDao(LogoPrint.class, logoPrintDao);
        registerDao(Emergency.class, emergencyDao);
        registerDao(LastSync.class, lastSyncDao);
        registerDao(BankAccountOfBranch.class, bankAccountOfBranchDao);
        registerDao(Broadcast.class, broadcastDao);
        registerDao(ReceiptHistory.class, receiptHistoryDao);
    }
    
    public void clear() {
        collectionActivityDaoConfig.getIdentityScope().clear();
        installmentScheduleDaoConfig.getIdentityScope().clear();
        mobileDataFileDaoConfig.getIdentityScope().clear();
        generalParameterDaoConfig.getIdentityScope().clear();
        groupUserDaoConfig.getIdentityScope().clear();
        lookupDaoConfig.getIdentityScope().clear();
        syncDaoConfig.getIdentityScope().clear();
        menuDaoConfig.getIdentityScope().clear();
        printItemDaoConfig.getIdentityScope().clear();
        questionSetDaoConfig.getIdentityScope().clear();
        schemeDaoConfig.getIdentityScope().clear();
        timelineTypeDaoConfig.getIdentityScope().clear();
        userDaoConfig.getIdentityScope().clear();
        kompetisiDaoConfig.getIdentityScope().clear();
        loggerDaoConfig.getIdentityScope().clear();
        collectionHistoryDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        depositReportDDaoConfig.getIdentityScope().clear();
        depositReportHDaoConfig.getIdentityScope().clear();
        imageResultDaoConfig.getIdentityScope().clear();
        locationInfoDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
        paymentHistoryDDaoConfig.getIdentityScope().clear();
        paymentHistoryHDaoConfig.getIdentityScope().clear();
        paymentChannelDaoConfig.getIdentityScope().clear();
        printResultDaoConfig.getIdentityScope().clear();
        receiptVoucherDaoConfig.getIdentityScope().clear();
        taskSummaryDaoConfig.getIdentityScope().clear();
        taskDDaoConfig.getIdentityScope().clear();
        taskHDaoConfig.getIdentityScope().clear();
        taskHSequenceDaoConfig.getIdentityScope().clear();
        planTaskDaoConfig.getIdentityScope().clear();
        timelineDaoConfig.getIdentityScope().clear();
        mobileContentDDaoConfig.getIdentityScope().clear();
        mobileContentHDaoConfig.getIdentityScope().clear();
        holidayDaoConfig.getIdentityScope().clear();
        printDateDaoConfig.getIdentityScope().clear();
        errorLogDaoConfig.getIdentityScope().clear();
        accountDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        groupTaskDaoConfig.getIdentityScope().clear();
        catalogueDaoConfig.getIdentityScope().clear();
        themeItemDaoConfig.getIdentityScope().clear();
        themeDaoConfig.getIdentityScope().clear();
        logoPrintDaoConfig.getIdentityScope().clear();
        emergencyDaoConfig.getIdentityScope().clear();
        lastSyncDaoConfig.getIdentityScope().clear();
        bankAccountOfBranchDaoConfig.getIdentityScope().clear();
        broadcastDaoConfig.getIdentityScope().clear();
        receiptHistoryDaoConfig.getIdentityScope().clear();
    }

    public CollectionActivityDao getCollectionActivityDao() {
        return collectionActivityDao;
    }

    public InstallmentScheduleDao getInstallmentScheduleDao() {
        return installmentScheduleDao;
    }

    public MobileDataFileDao getMobileDataFileDao() {
        return mobileDataFileDao;
    }

    public GeneralParameterDao getGeneralParameterDao() {
        return generalParameterDao;
    }

    public GroupUserDao getGroupUserDao() {
        return groupUserDao;
    }

    public LookupDao getLookupDao() {
        return lookupDao;
    }

    public SyncDao getSyncDao() {
        return syncDao;
    }

    public MenuDao getMenuDao() {
        return menuDao;
    }

    public PrintItemDao getPrintItemDao() {
        return printItemDao;
    }

    public QuestionSetDao getQuestionSetDao() {
        return questionSetDao;
    }

    public SchemeDao getSchemeDao() {
        return schemeDao;
    }

    public TimelineTypeDao getTimelineTypeDao() {
        return timelineTypeDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

    public KompetisiDao getKompetisiDao() {
        return kompetisiDao;
    }

    public LoggerDao getLoggerDao() {
        return loggerDao;
    }

    public CollectionHistoryDao getCollectionHistoryDao() {
        return collectionHistoryDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public DepositReportDDao getDepositReportDDao() {
        return depositReportDDao;
    }

    public DepositReportHDao getDepositReportHDao() {
        return depositReportHDao;
    }

    public ImageResultDao getImageResultDao() {
        return imageResultDao;
    }

    public LocationInfoDao getLocationInfoDao() {
        return locationInfoDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

    public PaymentHistoryDDao getPaymentHistoryDDao() {
        return paymentHistoryDDao;
    }

    public PaymentHistoryHDao getPaymentHistoryHDao() {
        return paymentHistoryHDao;
    }

    public PaymentChannelDao getPaymentChannelDao() {
        return paymentChannelDao;
    }

    public PrintResultDao getPrintResultDao() {
        return printResultDao;
    }

    public ReceiptVoucherDao getReceiptVoucherDao() {
        return receiptVoucherDao;
    }

    public TaskSummaryDao getTaskSummaryDao() {
        return taskSummaryDao;
    }

    public TaskDDao getTaskDDao() {
        return taskDDao;
    }

    public TaskHDao getTaskHDao() {
        return taskHDao;
    }

    public TaskHSequenceDao getTaskHSequenceDao() {
        return taskHSequenceDao;
    }

    public PlanTaskDao getPlanTaskDao() {
        return planTaskDao;
    }

    public TimelineDao getTimelineDao() {
        return timelineDao;
    }

    public MobileContentDDao getMobileContentDDao() {
        return mobileContentDDao;
    }

    public MobileContentHDao getMobileContentHDao() {
        return mobileContentHDao;
    }

    public HolidayDao getHolidayDao() {
        return holidayDao;
    }

    public PrintDateDao getPrintDateDao() {
        return printDateDao;
    }

    public ErrorLogDao getErrorLogDao() {
        return errorLogDao;
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public GroupTaskDao getGroupTaskDao() {
        return groupTaskDao;
    }

    public CatalogueDao getCatalogueDao() {
        return catalogueDao;
    }

    public ThemeItemDao getThemeItemDao() {
        return themeItemDao;
    }

    public ThemeDao getThemeDao() {
        return themeDao;
    }

    public LogoPrintDao getLogoPrintDao() {
        return logoPrintDao;
    }

    public EmergencyDao getEmergencyDao() {
        return emergencyDao;
    }

    public LastSyncDao getLastSyncDao() {
        return lastSyncDao;
    }

    public BankAccountOfBranchDao getBankAccountOfBranchDao() {
        return bankAccountOfBranchDao;
    }

    public BroadcastDao getBroadcastDao() {
        return broadcastDao;
    }

    public ReceiptHistoryDao getReceiptHistoryDao() {
        return receiptHistoryDao;
    }

}
