name : AI Code Reviewer

on: 
  pull_request:
    types:
      -open
      -synchronize

permissions: write-all
jobs: 
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: AI Code Reviewer
        uses: Shubhadarsini/ai-code-reviewer@main

        with: 
          GITHUB_TOKEN: {{secrets.GITHUB_TOKEN}}
          OPENAI_API_KEY: {{secrets.OPENAI_API_KEY}}
          OPENAI_MODEL: "gpt-4"
          exclude: "**/*.json, **/*.md"